spring:
  datasource:
    username: postgres
    password: 'postgres'
    url: jdbc:postgresql://localhost:5432/notes_db

  jpa:
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect




